name: Playwright Tests

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: npm ci

      - run: npx playwright install --with-deps

      # 🔥 Start Angular app properly
      - name: Start App
        run: npm run start -- --host 0.0.0.0 &
      
      # 🔥 Wait with timeout (VERY IMPORTANT)
      - name: Wait for App
        run: npx wait-on http://localhost:4200 --timeout 60000

      - run: npx playwright test